name: "Pushbullet Notification"
branding:
  icon: "bell"
  color: "red"
description: "A Github action to push Pushbullet notifications to your devices"
author: "ShaunLWM"
inputs:
  PB_TOKEN:
    description: "The Pushbullet API token"
runs:
  using: "docker"
  image: "Dockerfile"
