name: Pushbullet Notification
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Pushbullet Notification
      uses: ShaunLWM/action-pushbullet@master
      env:
        PB_TOKEN: ${{ secrets.PB_TOKEN }}
        PB_TITLE: Build Complete
        PB_TEXT: Your project has been built.
